### ISSUE TITLE
Assets Directory

### ISSUE THREAD

**Issue by meghprkh** [greg-js/clg#1]
Feature request for option to generate the markdown file as index.md inside the assets directory. As otherwise it does not seem to work with my metalsmith blog and I find it neater too

**Comment by greg-js** [comment]
Thanks for the feature req and the PR! I originally intended make this project much more useful on many different static site generators but kind of ran out of steam after I implemented everything I needed for myself and got busy at a new job :)
Your contribution is very highly appreciated - I'm moving houses right now but I'll publish the change on npm when I get more free time this weekend or the next, thanks again!
